### ISSUE TITLE
Survey NullPointerError

### ISSUE THREAD

**Issue by alextac98** [wpi-poverty-stoplight/ps-advisor-app#34]
When rotating the survey, there is a null pointer error that crashes the application.

**Comment by bhylak** [comment]
Copy the stack trace here.

**Comment by alextac98** [comment]
```
01-27 17:04:22.687 30503-30503/org.fundacionparaguaya.advisorapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: org.fundacionparaguaya.advisorapp, PID: 30503
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fundacionparaguaya.advisorapp/org.fundacionparaguaya.advisorapp.activities.SurveyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.fundacionparaguaya.advisorapp.models.IndicatorOption.getImageUrl()' on a null object reference
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
                                                                                       at android.app.ActivityThread.-wrap18(Unknown Source:0)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.fundacionparaguaya.advisorapp.models.IndicatorOption.getImageUrl()' on a null object reference
                                                                                       at org.fundacionparaguaya.advisorapp.fragments.ChooseIndicatorFragment.onCreateView(ChooseIndicatorFragment.java:93)
                                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
                                                                                       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
                                                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
                                                                                       at android.app.Activity.performStart(Activity.java:7019)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699) 
                                                                                       at android.app.ActivityThread.-wrap18(Unknown Source:0) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                       at android.os.Looper.loop(Looper.java:164) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```
